### ISSUE TITLE
Prevent Deletion

### ISSUE THREAD

**Issue by sarfraznawaz2005** [legshooter/addel#5]
I am using below code but it seems deletion is not being prevented when user clicks on Cancel button:

    $('.addel-container').addel({
        events: {
            delete: function (event) {
                if (!window.confirm('Are you absolutely positive you would like to delete: ' + '"' + event.target.find(':input').val() + '"?')) {
                    console.log('Deletion prevented!');
                    event.preventDefault();
                }
            }
        }
    });

Even the example given in original docs called example.html has the same problem.

Any idea on how to prevent deletion on delete event if user clicks on Cancel button ?

Thanks

**Comment by kobykorman** [comment]
Thanks for reporting, this is now a confirmed bug. I will release a new version to fix this soon.

**Comment by kobykorman** [comment]
Just released `v1.3.1` that fixes this bug.

**Comment by sarfraznawaz2005** [comment]
cool thanks
