### ISSUE TITLE
how to limit generation of inputs?

### ISSUE THREAD

**Issue by kintechGroup** [legshooter/addel#7]
hi thank you for perfect code...

i can limit number of input?
for example 10 input

**Comment by kobykorman** [comment]
Happy you enjoy it.

You mean the max amount of `target`s added?

There's nothing built-in, you'd need to implement it yourself.

You could do something along these lines:

```js
$('.addel-container').addel({
    
    // other options

    events: {
        add: function (event) {
            if ($('.addel-target').length == 10) {
                event.preventDefault();
            }
        }
    }
});
```
